name: MSBuild

on:
  workflow_dispatch:

jobs:
  test:
    name: Simple msg
    runs-on: windows-latest
    steps:
    - name: print a message
      env:
        var: "hello world"

        
      run: $var



