name: MSBuild

on: [push]

jobs:
  test:
    name: Simple msg
    runs-on: windows-latest
    steps:
    - name: print a message
      env:
        var1: "hello"
        var2: "world"
        
      run: echo $var1 $var2


