name: MSVC build

on:
  workflow_dispatch:

jobs:
  algorithms:
    name: Algorithms math build 
    runs-on: windows-latest
    steps:
    - name: Checkout doxygen
      uses: actions/checkout@v1
    - name: display path
      run: echo ${env::PATH}
      shell: powershell
      
  qt_visualisation:
    needs: algorithms
    name: Qt visualisation app build
    runs-on: windows-latest  
    steps:
    - name: Checkout doxygen
      uses: actions/checkout@v1
    - name: display path
      run: echo ${env::PATH}
      shell: powershell


